# Generated by Django 4.0.5 on 2022-06-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_day', models.CharField(blank=True, max_length=20, null=True)),
                ('food', models.CharField(max_length=20)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feeding_schedule',
                'managed': False,
            },
        ),
    ]
